#!/bin/sh
ln -sf {{pkg.path}}/package.json {{pkg.svc_var_path}}
ln -sf {{pkg.path}}/app.js {{pkg.svc_var_path}}
ln -sf {{pkg.path}}/node_modules {{pkg.svc_var_path}}
ln -sf {{pkg.path}}/lib {{pkg.svc_var_path}}
ln -sf {{pkg.path}}/controllers {{pkg.svc_var_path}}
ln -sf {{pkg.svc_config_path}}/config.json {{pkg.svc_var_path}}
